### ISSUE TITLE
Add ISPRS template

### ISSUE THREAD

**Issue by nikkopante** [myst-templates/templates#21]
https://www.isprs.org/documents/orangebook/app5.aspx

**Comment by rowanc1** [comment]
Hi @nikkopante,

We have done an initial push on this template, and it is working pretty well so far! You can use it with MyST documents using:

```yaml
---
exports:
  - format: pdf
    template: isprs
---
```

Let us know how you get on! Closing this issue here and we can fine-tune the template here:
- https://github.com/myst-templates/isprs

Current options:
![image](https://user-images.githubusercontent.com/913249/225452793-54aa2485-daaa-4cbf-9dae-c227c5595eb7.png)


Screenshot of using this with [this example](https://github.com/simpeg/tle-finitevolume):
![image](https://user-images.githubusercontent.com/913249/225452278-08ff9755-5268-4cd0-b091-3412f64e5176.png)

**Comment by nikkopante** [comment]
Thank you @rowanc1 :) .
